name: linting, testing, building
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  pipeline:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     node-version: [18]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          file: Dockerfile
          push: false
          tags: user/app:latest
      - name: build production project
        run: yarn build:prod
        if: always()
      - name: linting typescript
        run: yarn lint:ts
        if: always()
      - name: linting css
        run: yarn lint:scss
        if: always()
      - name: unit testing
        run: yarn test:unit
        if: always()
      - name: build storybook
        run: yarn storybook:build
        if: always()
      - name: update loki
        run: yarn loki update
        if: always()
      - name: screenshot testing
        run: yarn test:ui:ci
        if: always()
